export const environment = {
  production: false,
  title: 'Reimpresion',
  env: 'Development',
  version: '3.0.0-beta',
  
 
vistaCI: '/Everesttest/cisign', 
URLHc: "/Apieveresttest/APIHCHealth",
URLParametrizacion: "/Apieveresttest/APIParametrizacionGeneralHealth",
URLPaciente: "/Apieveresttest/APIPacienteV2",
URLMedico: "/Apieveresttest/APIMedicoHealth",
URLImpresion: "/Apieveresttest/APIImpresion",
UrlOrdenamiento: "/Apieveresttest/APIOrdenamientoHealth",
UrlOrdenamientoV2: "/Apieveresttest/ApiOrdenamientoV2",
UrlLogin: "/Apieveresttest/EverHealth",
UrlPrestador: "https://appportal.everestintelligent.com/APIPrestadoresHealth",
UrlTeleconsulta: "https://appcita.viva1a.com.co:8051/teleconsulta",
URLExtension: "https://appcita.viva1a.com.co:8051/Directorioclicktocallapi/api",
UrlCIsign: "/Apieveresttest/APIConsentimientoInformado/api",
  // Vista externa de Historia Clínica (configurar según despliegue)
  vistaHC: "",
URLApiCorreo: "/Apieveresttest/APIEnvioCorreo/api",
URLWhatsapp:"/Apieveresttest/ApiWhatsapp",
UrlIntegracionDigiturno: "/Apieveresttest/ApiIntegracionEverestDigiturno/api",
UrlParametrizacionRecurso: "/Apieveresttest/APIParametrizacionRecurso",
UrlAgendamiento: "",
IdPais:1,
UrlPdf: "/Apieveresttest/ApiImpresionUnificada/api/Prints",
numeroCliente:'1',
//tituloCliente:'DELTA',
telefonocliente:'5756475610',
plantillaCliente:'c2e0eac5-bfd5-4f3c-96a4-5e3e73d7e7ea',
tituloCliente:'Viva1A Ips',
//telefonocliente:'573011347279',
//plantillaCliente:'a88bc7e7-24eb-474b-9f0c-0d56b793b407',
 apiReal: 'http://172.27.83.196:82/Apieveresttest' // o tu servidor real
};
