export const environment = {
  production: false,
  title: 'Ordenamientos',
  env: 'Development',
  version: '3.0.0-beta',
  
 
vistaCI: '/everest_test/cisign', 
URLHc: "/APIHCHealth",
URLParametrizacion: "/APIParametrizacionGeneralHealth",
URLPaciente: "/APIPacienteV2",
URLMedico: "/APIMedicoHealth",
URLImpresion: "/APIImpresion",
UrlOrdenamiento: "/APIOrdenamientoHealth",
UrlOrdenamientoV2: "/ApiOrdenamientoV2",
UrlLogin: "/EverHealth",
UrlPrestador: "https://appportal.everestintelligent.com/APIPrestadoresHealth",
UrlTeleconsulta: "https://appcita.viva1a.com.co:8051/teleconsulta",
URLExtension: "https://appcita.viva1a.com.co:8051/Directorioclicktocallapi/api",
UrlCIsign: "/APIConsentimientoInformado/api",
  // Vista externa de Historia Clínica (configurar según despliegue)
  vistaHC: "",
URLApiCorreo: "/APIEnvioCorreo/api",
URLWhatsapp:"/ApiWhatsapp",
UrlIntegracionDigiturno: "/ApiIntegarcionEverestDigiturnoPrueba/api",
UrlParametrizacionRecurso: "/APIParametrizacionRecurso",
UrlAgendamiento: "",
IdPais:1,
UrlPdf: "/ApiImpresionUnificada/api/Prints",
//tituloCliente:'EVEREST',
numeroCliente:'1',
//telefonocliente:'573011347279',
//plantillaCliente:'a88bc7e7-24eb-474b-9f0c-0d56b793b407',
tituloCliente:'Viva1A Ips',
telefonocliente:'573011347279',
plantillaCliente:'a88bc7e7-24eb-474b-9f0c-0d56b793b407',
 apiReal: 'http://172.27.83.196:84' // o tu servidor real
};
