export const environment = {
  production: true,
  title: 'Ordenamientos',
  env: 'Production',
  version: '3.0.0-beta',

  vistaCI: '/delta_test/cisign',  
 URLHc: "/APIHCHealth",
URLParametrizacion: "/APIParametrizacionGeneralHealth",
URLPaciente: "/APIPacienteV2",
URLMedico: "/APIMedicoHealth",
URLImpresion: "/APIImpresion",
UrlOrdenamiento: "/APIOrdenamientoHealth",
UrlOrdenamientoV2: "/ApiOrdenamientoV2",
UrlLogin: "/EverHealth",
UrlPrestador: "https://appportal.everestintelligent.com/APIPrestadoresHealth",
UrlTeleconsulta: "https://appcita.viva1a.com.co:8051/teleconsulta",
URLExtension: "https://appcita.viva1a.com.co:8051/Directorioclicktocallapi/api",
UrlCIsign: "/APIConsentimientoInformadoTs/api",
  // Vista externa de Historia Clínica (configurar según despliegue)
  vistaHC: "",
URLApiCorreo: "/APIEnvioCorreo/api",
URLWhatsapp:"/apiperez_test/ApiWhatsapp",
UrlIntegracionDigiturno: "/ApiIntegarcionEverestDigiturnoPrueba/api",
UrlParametrizacionRecurso: "/APIParametrizacionRecurso",
UrlAgendamiento: "",
IdPais:1,
UrlPdf: "/apidelta_test/ApiImpresionUnificada/api/Prints",
tituloCliente:'DELTA',
numeroCliente:'1',
plantillaCliente:'c2e0eac5-bfd5-4f3c-96a4-5e3e73d7e7ea'
};
