export const DEFAULT_TABLE_PAGE_SIZE = 5;

export const ISO_DATE_ONLY_LENGTH = 10;

export const PROFESIONAL_SEARCH_MIN_LENGTH = 3;
export const PROFESIONAL_SEARCH_DEBOUNCE_MS = 350;
export const MAX_PROFESIONALES_VISIBLE = 300;

export const TIPO_DOCUMENTO_DEFAULT_RETRY_MAX = 20;
export const TIPO_DOCUMENTO_DEFAULT_RETRY_DELAY_MS = 150;

export const LLAMADO_ESTADO_POLL_MS = 1000;

export const TIMEOUT_PROFESIONALES_MS = 8000;
export const TIMEOUT_DESACTIVAR_CITA_MS = 15000;
export const TIMEOUT_LLAMAR_TURNO_MS = 20000;
